language: haskell

branches:
  only:
    - master

sudo: required
cache:
  directories:
    - $HOME/.stack/

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry wget https://github.com/commercialhaskell/stack/releases/download/v0.1.6.0/stack-0.1.6.0-linux-x86_64.tar.gz
  - tar xzf stack-0.1.6.0-linux-x86_64.tar.gz
  - cd stack-0.1.6.0-linux-x86_64/
  - cp ./stack ~/.local/bin/
  - chmod a+x ~/.local/bin/stack
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
    #- wget http://libsdl.org/release/SDL2-2.0.4.tar.gz -O - | tar xz
    #- cd SDL2-2.0.4 && ./configure && make -j && sudo make install && cd ..


install:
  - stack setup
  - stack build

script:
  - stack test
  - stack bench
