flags: {}
packages:
- '.'
- location:
    git: http://github.com/oldmanmike/hs-minecraft-nbt
    commit: 2ac6813af4dd7b749065b19946d21a650a93de49
extra-deps:
  - ekg-json-0.1.0.2
resolver: nightly-2016-06-30
