port: 25567
rootDir: "/home/oldmanmike/opensandbox"
configDir: "configs"
backupDir: "backups"
logDir: "logs"
worldDir: "world"
mcVersion: "1.10"
maxPlayers: 20
viewDistance: 10
maxBuildHeight: 256
gameMode: "Survival"
dimension: "Overworld"
difficulty: "Normal"
worldType: "Flat"
motd: "A OpenSandbox Server"
encryption: false
compression: false
monitoring: true
enabled: true
